name: MobLimiter
main: us.corenetwork.moblimiter.MobLimiter
version: 2.0
author: matejdro
commands:
    animals:
        description: Nearby animals.
    villagers:
        description: Nearby villagers.